### ISSUE TITLE
ハードウェア開発

### ISSUE THREAD

**Issue by lion-rion** [jphacks/KB_2316#3]
- [x]  3Dプリンタで皮を作成する

## マイコンのプログラム

- [x] 回路の構築
- [x] PINの設定をする
- [x] Wifiの接続を行う
- [x] 超音波センサで値の取得
- [x] 前回検出した値を比較できる状態にする
- [x] 前回検出した値から5cm以上差があればHTTPリクエストを送信する
- [x] main関数の作成

**Comment by mio818** [comment]
done!!
